import { Schema, Table, column } from '@powersync/react-native';

export const AppSchema = new Schema({
  profiles: new Table({
    fullname: column.text,
    email: column.text,
    role: column.text,
    phone_number: column.text,
    avatar_url: column.text,
    created_at: column.text,
  }),
  businesses: new Table({
    name: column.text,
    owner_id: column.text,
    join_code: column.text,
    logo_url: column.text,
    address: column.text,
    is_active: column.integer,
    created_at: column.text,
  }),
  branches: new Table({
    business_id: column.text,
    name: column.text,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  business_members: new Table({
    business_id: column.text,
    user_id: column.text,
    role: column.text,
    branch_id: column.text,
    is_active: column.integer,
    joined_at: column.text,
  }),
  categories: new Table({
    business_id: column.text,
    name: column.text,
  }),
  products: new Table({
    business_id: column.text,
    category_id: column.text,
    name: column.text,
    barcode: column.text,
    sku: column.text,
    selling_price: column.real,
    cost_price: column.real,
    image_url: column.text,
    is_active: column.integer,
    is_archived: column.integer,
    version: column.integer,
    description: column.text,
    created_at: column.text,
    updated_at: column.text,
    created_by: column.text,
    last_modified_by: column.text,
  }),
  fallback_products: new Table(
    {
      business_id: column.text,
      category_id: column.text,
      name: column.text,
      barcode: column.text,
      sku: column.text,
      selling_price: column.real,
      cost_price: column.real,
      image_url: column.text,
      is_active: column.integer,
      is_archived: column.integer,
      version: column.integer,
      description: column.text,
      created_at: column.text,
      updated_at: column.text,
      created_by: column.text,
      last_modified_by: column.text,
    },
    { localOnly: true },
  ),
  inventory_items: new Table({
    product_id: column.text,
    branch_id: column.text,
    business_id: column.text,
    stock_quantity: column.integer,
    low_stock_threshold: column.integer,
    updated_at: column.text,
  }),
  fallback_inventory_items: new Table(
    {
      product_id: column.text,
      branch_id: column.text,
      business_id: column.text,
      stock_quantity: column.integer,
      low_stock_threshold: column.integer,
      updated_at: column.text,
    },
    { localOnly: true },
  ),
  inventory_logs: new Table({
    product_id: column.text,
    branch_id: column.text,
    action_type: column.text,
    quantity_before: column.integer,
    quantity_changed: column.integer,
    quantity_after: column.integer,
    reference_type: column.text,
    reference_id: column.text,
    performed_by: column.text,
    created_at: column.text,
  }),
  sales: new Table({
    business_id: column.text,
    branch_id: column.text,
    employee_id: column.text,
    total_amount: column.real,
    discount_amount: column.real,
    payment_method: column.text,
    status: column.text,
    notes: column.text,
    created_at: column.text,
    synced_at: column.text,
    reference_number: column.text,
    vat_amount: column.real,
    idempotency_key: column.text,
  }),
  sale_items: new Table({
    sale_id: column.text,
    product_id: column.text,
    business_id: column.text,
    quantity: column.integer,
    unit_price: column.real,
    subtotal: column.real,
  }),
  payments: new Table({
    sale_id: column.text,
    business_id: column.text,
    method: column.text,
    amount_peso: column.real,
  }),
  refunds: new Table({
    idempotency_key: column.text,
    original_sale_id: column.text,
    branch_id: column.text,
    business_id: column.text,
    reason: column.text,
    total_peso: column.real,
    created_at: column.text,
    created_by: column.text,
    source_device_id: column.text,
    reference_number: column.text,
  }),
  refund_items: new Table({
    refund_id: column.text,
    sale_item_id: column.text,
    product_id: column.text,
    quantity: column.integer,
    unit_price: column.real,
    subtotal: column.real,
  }),
  audit_logs: new Table({
    business_id: column.text,
    branch_id: column.text,
    actor_id: column.text,
    event_type: column.text,
    payload: column.text,
    created_at: column.text,
    source_device_id: column.text,
  }),
  device_sessions: new Table({
    user_id: column.text,
    business_id: column.text,
    device_id: column.text,
    device_name: column.text,
    last_seen_at: column.text,
    created_at: column.text,
  }),
});
